### ISSUE TITLE
Invisible AI

### ISSUE THREAD

**Issue by JamieKG** [dayzai/A3XAI#1]
HI face on two occasions I have had reports of AI not dyeing when being run over yes I have the setting for no AI damage on but I spectated the player and could not see the ai for myself and on one occasion I teleported  to the players vehicle got out and was shoot and killed buy the AI that was invisible to me but he could see him 

Thanks JamieKG

**Comment by dayzai** [comment]
A3XAI does not use any commands that could make AI invisible. It's most likely an Arma 3 issue of some sort.
