### ISSUE TITLE
Error Undefined variable in expression:

### ISSUE THREAD

**Issue by jus61** [dayzai/A3XAI#10]
11:38:58 Error in expression <Statements = call {
if (_searchLoot && {_max_dist > 100}) exitWith {format ["if >
11:38:58   Error position: <_max_dist > 100}) exitWith {format ["if >
11:38:58   Error Undefined variable in expression: _max_dist
11:38:58 File A3XAI\compile\A3XAI_behavior\A3XAI_BIN_taskPatrol.sqf, line 63
11:38:58 Error in expression <his] call A3XAI_selectRandomWaypoint};",_randomizeChance]
};
 
_wpTimeouts = if (>
11:38:58   Error position: <_randomizeChance]
};
 
_wpTimeouts = if (>
11:38:58   Error Undefined variable in expression: _randomizechance
11:38:58 File A3XAI\compile\A3XAI_behavior\A3XAI_BIN_taskPatrol.sqf, line 65
11:38:58 Error in expression <hicle) then {(25 + _slack)} else {(10 + _slack)};
if ( _slack < 20 ) then { _sla>
11:38:58   Error position: <_slack)};
if ( _slack < 20 ) then { _sla>
11:38:58   Error Undefined variable in expression: _slack
11:38:58 File A3XAI\compile\A3XAI_behavior\A3XAI_BIN_taskPatrol.sqf, line 83
11:38:58 Error in expression < = random 180;
while {count _wp_array < _wp_count} do 
{
private ["_x1","_y1","_>
11:38:58   Error position: <_wp_count} do 
{
private ["_x1","_y1","_>
11:38:58   Error Undefined variable in expression: _wp_count
11:38:58 File A3XAI\compile\A3XAI_behavior\A3XAI_BIN_taskPatrol.sqf, line 87
11:38:58 Error in expression <= (behaviour (leader _unitGroup));
 
if (_max_dist < 75) then {_unitGroup setSpee>
11:38:58   Error position: <_max_dist < 75) then {_unitGroup setSpee>
11:38:58   Error Undefined variable in expression: _max_dist
11:38:58 File A3XAI\compile\A3XAI_behavior\A3XAI_BIN_taskPatrol.sqf, line 57
11:38:59 Error in expression <.5;
};
 
uiSleep 1;
 
for "_i" from 1 to (_wp_count - 1) do
{
private ["_wp","_cur>
11:38:59   Error position: <_wp_count - 1) do
{
private ["_wp","_cur>
11:38:59   Error Undefined variable in expression: _wp_count
11:38:59 File A3XAI\compile\A3XAI_behavior\A3XAI_BIN_taskPatrol.sqf, line 192

**Comment by dayzai** [comment]
Fixed in 0.1.7

**Comment by jus61** [comment]
THX
