### ISSUE TITLE
AI Vehicles not spawning

### ISSUE THREAD

**Issue by Ericode18** [dayzai/A3XAI#12]
Hello, I have the ai vheicles set for 30 as shown here:
A3XAI_maxLandPatrols = 30;
but none are spawning. I updated to arma 1.52 and this is when the issue began, before the update it worked fine.

**Comment by TheDanius** [comment]
Check the discussion on the Exile forums. 1.52 caused an issue with how the mod access the config file. The issue cause all of the settings to be reset to default. An official fix has been announced by Face to be incoming soon and a user has posted a work around on the exile forum discussion.
