### ISSUE TITLE
A3XAI convoy vehicles can get to a state of invincibility

### ISSUE THREAD

**Issue by moosemilker** [dayzai/A3XAI#14]
Some players have reported a very rare case where convoy trucks can get to a state of invincibility.  The config setting that turns the AI type I am referring to is:

//Global maximum number of active AI land vehicle patrols. Set at 0 to disable (Default: 0).	
A3XAI_maxLandPatrols = 7;

The odd bit is, they trapped the AI, shot them up a bunch, encountered invincibility issue, moved on, I asked them to track them down again and take screenshots, they tracked the same convoy down (they told me the AI was stuck on something / they were 100% sure it was the same convoy), they shot the AI up again and they were no longer invincible...

I run this setting on Altis, and players (that play this game to the extreme) encounter this issue on a very rarely.  There is a chance this is already patched, since I am running version: 0.1.7.2

I will try an update to the latest version as soon as I can find time.

-Aaron
http://moosemilker.com

**Comment by dayzai** [comment]
AI are made nom hostile and damage immune if they are within 900m of any trader area.

**Comment by moosemilker** [comment]
Gotcha.  Thanks.  I will check if this is the case, and closing this.
