### ISSUE TITLE
Ai land patrols crash into objects

### ISSUE THREAD

**Issue by JamieKG** [dayzai/A3XAI#2]
I use the map Taviana and the land patrols crash into objects in the road

Thanks JamieKG

**Comment by dayzai** [comment]
This is an Arma 3 problem, AI drivers have always been bad at pathing. A3XAI does not control AI pathing and so, not solvable with scripting.

**Comment by jus61** [comment]
should help you JamieKG

https://forums.bistudio.com/topic/177206-vcom-ai-driving-mod/
