### ISSUE TITLE
Ai carry First Aid Kits

### ISSUE THREAD

**Issue by JamieKG** [dayzai/A3XAI#4]
The ai carry alot of First Aid Kits i tried to blacklist them via
A3XAI_dynamicLootList = true;
A3XAI_dynamicLootBlacklist = ["FirstAidKit"];
 but they are still there

**Comment by dayzai** [comment]
If you are using DMS, the current version transfers all AI to another client (HC?), including AI spawned by A3XAI. This causes A3XAI to be unable to remove the First Aid Kits, which are used for the AI self-healing.

For now you can remove the kits by setting A3XAI_enableHealing false in your A3XAI config.

**Comment by JamieKG** [comment]
Ok thanks man I am using dms
