### ISSUE TITLE
Air Patrols not spawning

### ISSUE THREAD

**Issue by JamieKG** [dayzai/A3XAI#5]
I have my air patrols set to 
A3XAI_maxHeliPatrols = 4;
and none are spawning I did notice this in my logs

16:57:13 Error in expression <
_heliType = (A3XAI_heliList select _i) select 0;
_amount = (A3XAI_heliList sele>
16:57:13   Error position: <select 0;
_amount = (A3XAI_heliList sele>
16:57:13   Error Generic error in expression
16:57:13 File A3XAI\scripts\setup_veh_patrols.sqf, line 7

Thanks JamieKG

**Comment by dayzai** [comment]
What other settings have you changed in the config?

**Comment by JamieKG** [comment]
I changed the air vehicles to exile ones

**Comment by JamieKG** [comment]
im afraid the issue was between keyboard and chair error in config
