### ISSUE TITLE
AI do not want to die

### ISSUE THREAD

**Issue by jus61** [dayzai/A3XAI#6]
I sometimes have the problem that the AI will not die

https://www.youtube.com/watch?t=21&v=gOczH0kDcMQ

**Comment by jus61** [comment]
It happens only when the AI had a Helmet

**Comment by dayzai** [comment]
After testing, it was found that high armor equipment (helmet, vest, uniform) was responsible, not this is a not a bug.

**Comment by dayzai** [comment]
Disregard previous, confirmed as bug and will fix.
