### ISSUE TITLE
min / max distance to the player when the AI Spawn

### ISSUE THREAD

**Issue by jus61** [dayzai/A3XAI#7]
Could you enter the settings for min / max distance to the player when the AI Spawn (Static, Dynamic Spawn)

The problem is that the AI sometimes 2m next Player Spawns

**Comment by dayzai** [comment]
A3XAI's minimum spawn distance is between 200-300m from any player for all spawn types. Are you absolutely certain that the AI were spawned by A3XAI?

**Comment by jus61** [comment]
Yas i am absolutely certain

**Comment by dayzai** [comment]
I am looking into this and will be releasing an update soon.

**Comment by dayzai** [comment]
The relocation for stuck infantry AI units did not check for nearby players. I updated A3XAI to 0.1.2 to fix this issue.

I will now be closing this issue. If the problem continues, please reopen this issue.

**Comment by jus61** [comment]
Thx
