### ISSUE TITLE
Error in expression HC Client @A3XAI

### ISSUE THREAD

**Issue by jus61** [dayzai/A3XAI#9]
Hmm i have an error in the HC client RPR

14:44:47 Could not load 'ExileClient_object_player_event_onPlayerRespawn'. Extension not listed in allowedPreprocessFileExtensions
14:44:47 "HC/BIS_fnc_log: [BIS_fnc_selectRespawnTemplate] onPlayerRespawn template 'Exile' executed from file 'ExileClient_object_player_event_onPlayerRespawn'"
14:44:47 Error in expression <tOxygenRemaining player; 

BIS_SuffCC ppEffectAdjust [1,1,0,[0.0090>
14:44:47   Error position: <BIS_SuffCC ppEffectAdjust [1,1,0,[0.0090>
14:44:47   Error Undefined variable in expression: bis_suffcc

**Comment by jus61** [comment]
15:04:46 Error in expression <lar",0.70],["NVGoggles",0.20]]]
];

if (A3XAI_verifySettings) then {
if !(A3XAI_>
15:04:46   Error position: <A3XAI_verifySettings) then {
if !(A3XAI_>
15:04:46   Error Undefined variable in expression: a3xai_verifysettings
15:04:46 File A3XAI\scripts\verifySettings.sqf, line 298
15:04:46 "[A3XAI] Compiling functions..."
15:04:46 "[A3XAI] A3XAI HC functions loaded."
15:04:46 "[A3XAI] Compiling A3XAI functions."
15:04:46 Error in expression <rifySettings.sqf",A3XAI_directory];
if (_readOverrideFile) then {call compile pr>
15:04:46   Error position: <_readOverrideFile) then {call compile pr>
15:04:46   Error Undefined variable in expression: _readoverridefile
15:04:46 File A3XAI\init\A3XAI_inithc.sqf, line 69
15:04:46 "[A3XAI] A3XAI functions compiled."
15:04:46 "[A3XAI] A3XAI HC PVEHs loaded."
15:04:46 "[A3XAI] A3XAI settings: Debug Level: 0. WorldName: altis. VerifyClassnames: true. VerifySettings: any."
15:04:46 Error in expression <Lower worldName),A3XAI_verifyClassnames,A3XAI_verifySettings];


_setupLocations>
15:04:46   Error position: <A3XAI_verifySettings];


_setupLocations>
15:04:46   Error Undefined variable in expression: a3xai_verifysettings
15:04:46 File A3XAI\init\A3XAI_inithc.sqf, line 80

**Comment by dayzai** [comment]
The errors in the first post are normal, you will always see some errors about oxygenRemaining.
I will look into the errors in your second post.

**Comment by jus61** [comment]
With the HC clients spawn no AI's

**Comment by dayzai** [comment]
HC doesn't spawn AI.

**Comment by jus61** [comment]
NO
